// ── Extinct species ───────────────────────────────────────────────
const extinctSpecies = [
  {
    key:        'mammoth',
    name:       'Woolly Mammoth',
    sci:        'Mammuthus primigenius',
    period:     'Pleistocene · ~4,000 BP', 
    cause:      'Rapid climate warming & human overhunting',
    habitat:    'Sub‑Arctic tundra/steppe',
    range:      'Siberia, N. Eurasia, N. America',
    diet:       'Grasses, herbs, shrubs',
    role:       'Ecosystem engineer',
    icon:       '🦣',
    cardColor:  '#e8f4e8',
    cardAccent: '#2d7a4a',
    heroColor:  '#1a5c35',
    heroLight:  '#e8f4e8',
    desc:       'The iconic Ice Age giant. Adapted to frigid steppe with dense wool, curved foraging tusks, and cold-adapted haemoglobin. Last populations survived on Wrangel Island until ~1650 BCE.',
  },
  {
    key:        'dodo',
    name:       'Dodo',
    sci:        'Raphus cucullatus',
    period:     'Holocene · ~1681 CE',
    cause:      'Hunting & introduced predators',
    habitat:    'Tropical coastal forest',
    range:      'Mauritius, Indian Ocean',
    diet:       'Fallen fruit, seeds, roots',
    icon:       '🦤',
    cardColor:  '#fef3e2',
    cardAccent: '#c47c1a',
    heroColor:  '#9a5c10',
    heroLight:  '#fef3e2',
    desc:       'Entirely flightless and fearless of humans — a trait that made it catastrophically easy to hunt. Closest living relative is the Nicobar Pigeon. Laid a single egg per season.',
  },
  {
    key:        'nfwolf',
    name:       'Newfoundland Wolf',
    sci:        'Canis lupus subspecies C.l. labradorius',
    period:     'Holocene · ~1930 CE',
    cause:      'Human overhunting & prey depletion',
    habitat:    'Boreal forest, taiga, & tundra',
    range:      'Newfoundland & Labrador, & northern Quebec, Canada',
    diet:       'Caribou, moose, Muskoxen',
    icon:       '🐺',
    cardColor:  '#eaf0fb',
    cardAccent: '#2a4fa0',
    heroColor:  '#1c3a7a',
    heroLight:  '#eaf0fb',
    desc:       'A subspecies of grey wolf adapted to island isolation. Key predator regulating caribou herds on Newfoundland. Extirpated by ~1930 through human persecution and prey collapse.',
  },
];
